service:
  name: ses-lambda-serverless

package:
  include:
    - app/**

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:
  h01ListVerifiedEmailsHandler:
    handler: handlers/01-list-verified-emails.handler.h01ListVerifiedEmailsHandler
    events:
      - http:
          method: GET
          path: list
  h02AddNewEmailHandler:
    handler: handlers/02-add-new-email.handler.h02AddNewEmailHandler
    events:
      - http:
          method: GET
          path: add
  h03SendMailHandler:
    handler: handlers/03-send-mail.handler.h03SendMailHandler
    events:
      - http:
          method: POST
          path: mail
  h04DeleteEmailHandler:
    handler: handlers/04-delete-email.handler.h04DeleteEmailHandler
    events:
      - http:
          method: GET
          path: delete
  
 
